rmdir /S /Q flac\bin
rmdir /S /Q flac\obj
rmdir /S /Q flacFs\bin
rmdir /S /Q flacFs\obj
rmdir /S /Q flacTest\bin
rmdir /S /Q flacTest\obj
rmdir /S /Q virtualFlac\bin
rmdir /S /Q virtualFlac\obj
rmdir /S /Q virtualFlacGen\bin
rmdir /S /Q virtualFlacGen\obj